// no_facade_test.go — Guards capture against lifecycle compatibility exports.

package capture

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCaptureHasNoCompatibilityAliases(t *testing.T) {
	t.Parallel()

	paths, err := filepath.Glob("*.go")
	if err != nil {
		t.Fatal(err)
	}
	var source strings.Builder
	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		contents, readErr := os.ReadFile(path)
		if readErr != nil {
			t.Fatalf("read %s: %v", path, readErr)
		}
		source.Write(contents)
	}
	for _, forbidden := range []string{
		"ForTest",
		"LifecycleEvent =",
		"LifecycleListener =",
		"LifecycleObserver =",
		"EventCircuitOpened =",
		"NewLifecycleObserver =",
		"ParseLifecycleEvent =",
		"SetLifecycleCallback(",
		"AddLifecycleCallback(",
		"func (c *Capture) SubscribeLifecycle(",
		"func (c *Capture) emitLifecycleEvent(",
		"func (c *Capture) SetServerVersion(",
		"func (c *Capture) GetServerVersion(",
		"func (c *Capture) GetVersionMismatch(",
		"func (c *Capture) SetFeaturesCallback(",
		"func (c *Capture) SetClientRegistry(",
		"func (c *Capture) GetClientRegistry(",
		"func (c *Capture) SetClientRegistryForTest(",
		"type Capture struct {\n\tmu ",
		"func (c *Capture) LoadSettingsFromDisk(",
		"QueryDispatcher =",
		"QuerySnapshot =",
		"NewQueryDispatcher =",
		"CircuitBreaker =",
		"HealthResponse =",
		"RateLimitResponse =",
		"NewCircuitBreaker =",
		"DebugLogger =",
		"NewDebugLogger =",
		"PlaybackSession =",
		"PlaybackResult =",
		"Coordinates =",
		"LogDiffResult =",
		"DiffLogEntry =",
		"ValueChange =",
		"ActionComparison =",
		"recordingStorageMax =",
		"recordingWarningLevel =",
		"validateRecordingID =",
		"calculateRecordingSize =",
		"ResourceEntry =",
		"ResourceDiff =",
		"CausalDiffResult =",
		"WSConnectionTracker =",
		"queryResultTTL =",
		"Store = Capture",
		"Snapshot = CaptureSnapshot",
		"WebSocketEvent =",
		"SamplingInfo =",
		"WebSocketEventFilter =",
		"WebSocketStatusFilter =",
		"WebSocketStatusResponse =",
		"WebSocketConnection =",
		"WebSocketClosedConnection =",
		"WebSocketMessageRate =",
		"WebSocketDirectionStats =",
		"WebSocketLastMessage =",
		"WebSocketMessagePreview =",
		"WebSocketSchema =",
		"WebSocketSamplingStatus =",
		"NetworkWaterfallEntry =",
		"NetworkWaterfallPayload =",
		"NetworkBody =",
		"NetworkBodyFilter =",
		"EnhancedAction =",
		"EnhancedActionFilter =",
		"ExtensionLog =",
		"PollingLogEntry =",
		"HTTPDebugEntry =",
		"BufferClearCounts =",
		"CompleteCommand(",
		"ExtensionStatus struct",
		"UpdateExtensionStatus(",
		"func (c *Capture) EventBuffers(",
		"func (c *Capture) NetworkWaterfallStore(",
		"func (c *Capture) ExtensionLogStore(",
		"func (c *Capture) PerformanceSnapshotStore(",
		"func (c *Capture) GetExtensionVersion(",
		"func (c *Capture) UnsubscribeLifecycle(",
		"func (c *Capture) SaveSettingsToDisk(",
		"func (c *Capture) ClearExtensionLogs(",
		"func (c *Capture) GetNetworkTimestamps(",
		"func (c *Capture) GetWebSocketTimestamps(",
		"func (c *Capture) GetActionTimestamps(",
		"func (c *Capture) GetWebSocketBufferMemory(",
		"func (c *Capture) GetNetworkBodiesBufferMemory(",
		"func (c *Capture) GetNetworkBodyCount(",
		"func (c *Capture) GetNetworkWaterfallCount(",
		"func (c *Capture) GetWebSocketEventCount(",
		"func (c *Capture) GetEnhancedActionCount(",
		"func (c *Capture) AddExtensionLogs(",
		"func (c *Capture) GetExtensionLogs(",
		"type ExtensionLogBuffer struct",
		"func (c *Capture) AddNetworkWaterfallEntries(",
		"func (c *Capture) GetNetworkWaterfallEntries(",
		"type NetworkWaterfallBuffer struct",
		"func (c *Capture) AddPerformanceSnapshots(",
		"func (c *Capture) GetPerformanceSnapshots(",
		"func (c *Capture) GetPerformanceSnapshotByURL(",
		"func (c *Capture) StoreBeforeSnapshot(",
		"func (c *Capture) GetAndDeleteBeforeSnapshot(",
		"func (c *Capture) CreatePendingQuery(",
		"func (c *Capture) CreatePendingQueryWithClient(",
		"func (c *Capture) CreatePendingQueryWithTimeout(",
		"func (c *Capture) GetPendingQueries(",
		"func (c *Capture) GetPendingQueriesForClient(",
		"func (c *Capture) WaitForPendingQueries(",
		"func (c *Capture) AcknowledgePendingQuery(",
		"func (c *Capture) SetQueryResult(",
		"func (c *Capture) SetQueryResultWithClient(",
		"func (c *Capture) SetQueryResultWithClientNoCommandComplete(",
		"func (c *Capture) TakeQueryResult(",
		"func (c *Capture) TakeQueryResultForClient(",
		"func (c *Capture) WaitForResult(",
		"func (c *Capture) WaitForResultWithClient(",
		"func (c *Capture) SetQueryTimeout(",
		"func (c *Capture) GetQueryTimeout(",
		"func (c *Capture) RegisterCommand(",
		"func (c *Capture) ApplyCommandResult(",
		"func (c *Capture) ExpireCommand(",
		"func (c *Capture) WaitForCommand(",
		"func (c *Capture) GetCommandResult(",
		"func (c *Capture) GetPendingCommands(",
		"func (c *Capture) GetCompletedCommands(",
		"func (c *Capture) GetFailedCommands(",
		"func (c *Capture) GetRecentCommandTraces(",
		"func (c *Capture) QueuePosition(",
		"func (c *Capture) QueueDepth(",
		"func (c *Capture) GetLastPendingQuery(",
		"var NewRecordingManager =",
		"func (c *Capture) StartRecording(",
		"func (c *Capture) StopRecording(",
		"func (c *Capture) AddRecordingAction(",
		"func (c *Capture) ListRecordings(",
		"func (c *Capture) GetRecording(",
		"func (c *Capture) StartPlayback(",
		"func (c *Capture) ExecutePlayback(",
		"func (c *Capture) DetectFragileSelectors(",
		"func (c *Capture) GetPlaybackStatus(",
		"func (c *Capture) DiffRecordings(",
		"func (c *Capture) CategorizeActionTypes(",
		"func (c *Capture) GetStorageInfo(",
		"func (c *Capture) DeleteRecording(",
		"func (c *Capture) RecalculateStorageUsed(",
		"func (c *Capture) RecordEvents(",
		"func (c *Capture) CheckRateLimit(",
		"func (c *Capture) GetHealthStatus(",
		"func (c *Capture) WriteRateLimitResponse(",
		"extensionState ExtensionState",
		"func (c *Capture) WaitForExtensionConnected(",
		"func (c *Capture) IsExtensionConnected(",
		"func (c *Capture) GetExtensionStatus(",
		"func (c *Capture) IsPilotEnabled(",
		"func (c *Capture) IsPilotActionAllowed(",
		"func (c *Capture) GetPilotStatus(",
		"func (c *Capture) GetInProgressCommands(",
		"func (c *Capture) GetTrackingStatus(",
		"func (c *Capture) UpdateTrackedTab(",
		"func (c *Capture) GetTrackedTabTitle(",
		"func (c *Capture) GetTabStatus(",
		"func (c *Capture) IsTrackedTabActive(",
		"func (c *Capture) SetTrackedTabActiveForTest(",
		"func (c *Capture) GetCSPStatus(",
		"func (c *Capture) SetSecurityMode(",
		"func (c *Capture) GetSecurityMode(",
		"func (c *Capture) GetActiveTestIDs(",
		"func (c *Capture) SetTestBoundaryStart(",
		"func (c *Capture) SetTestBoundaryEnd(",
		"func (c *Capture) SetPilotEnabled(",
		"func (c *Capture) SetPilotUnknownForTest(",
		"func (c *Capture) SetTrackingStatusForTest(",
		"func (c *Capture) SimulateExtensionConnectForTest(",
		"func (c *Capture) SimulateExtensionDisconnectForTest(",
		"func (c *Capture) SetTabStatusForTest(",
		"func (c *Capture) SetCSPStatusForTest(",
		"func (c *Capture) logPollingActivity(",
		"func (c *Capture) LogHTTPDebugEntry(",
		"func (c *Capture) GetHTTPDebugLog(",
		"func (c *Capture) redactHTTPDebugEntry(",
		"buffers BufferStore",
		"wsConnections wsconn.Tracker",
		"func (c *Capture) AddNetworkBodies(",
		"func (c *Capture) AddWebSocketEvents(",
		"func (c *Capture) AddEnhancedActions(",
		"func (c *Capture) GetNetworkBodies(",
		"func (c *Capture) GetAllWebSocketEvents(",
		"func (c *Capture) GetAllEnhancedActions(",
		"func (c *Capture) GetWebSocketEvents(",
		"func (c *Capture) GetWebSocketStatus(",
		"func (c *Capture) ClearNetworkBuffers(",
		"func (c *Capture) ClearWebSocketBuffers(",
		"func (c *Capture) ClearActionBuffer(",
		"func (c *Capture) GetNetworkTotalAdded(",
		"func (c *Capture) GetNetworkErrorTotalAdded(",
		"func (c *Capture) GetWebSocketTotalAdded(",
		"func (c *Capture) GetActionTotalAdded(",
		"func (c *Capture) GetSnapshot(",
		"func (c *Capture) NetworkWaterfall(",
		"func ExtractURLPath(",
	} {
		if strings.Contains(source.String(), forbidden) {
			t.Errorf("capture retains compatibility surface %q", forbidden)
		}
	}
}
