#!/usr/bin/env bash
# check-baseline-currency.sh — Fail when a ratchet baseline no longer matches the tree.
#
# Regeneration of each baseline below is deterministic for the same tree, so
# any byte difference after regenerating means the committed ratchet is stale
# (the tree improved and nobody re-froze it) or was hand-edited.
#
# .coverage-baseline.json is deliberately NOT checked here: it records
# measured test coverage, which can only be regenerated by a full
# `make test-cover` run — there is no tree-deterministic command to compare
# against. Its upward-only write path is guarded inside run-go-coverage.sh.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$PROJECT_ROOT"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# judge_baseline <baseline-file> <make-update-target> <regen-command...>
#
# The regen command overwrites the committed file in place, so the original
# bytes are backed up and restored on EVERY path (success or failure): the
# check reports drift, it never leaves a dirty tree.
judge_baseline() {
  local baseline="$1" update_target="$2"
  shift 2
  local backup="$WORK_DIR/$(basename "$baseline")"

  if [[ ! -f "$baseline" ]]; then
    echo "FAIL: $baseline is missing; run \`make $update_target\` and commit the result." >&2
    return 1
  fi
  cp "$baseline" "$backup"

  local regen_status=0
  "$@" || regen_status=$?
  if [[ "$regen_status" -ne 0 ]]; then
    cp "$backup" "$baseline"
    echo "FAIL: regenerating $baseline exited $regen_status; the committed file was restored." >&2
    return 1
  fi

  if cmp -s "$backup" "$baseline"; then
    cp "$backup" "$baseline"
    echo "OK: $baseline matches the tree."
    return 0
  fi

  (diff -u "$backup" "$baseline" || true) | sed -n '1,40p' >&2
  cp "$backup" "$baseline"
  echo "FAIL: $baseline is stale; run \`make $update_target\` and commit the result." >&2
  return 1
}

failures=0

judge_baseline \
  .function-length-baseline-go.json \
  function-length-baseline-update \
  go run ./scripts/contracts/complexity --update-length-baseline || failures=$((failures + 1))

judge_baseline \
  .function-length-baseline-ts.json \
  function-length-baseline-update \
  node scripts/quality/contracts/complexity/check-complexity.mjs --update-length-baseline || failures=$((failures + 1))

judge_baseline \
  .ts-strictness-baseline.json \
  ts-strictness-baseline-update \
  node scripts/quality/contracts/ts-strictness/check-ts-strictness.mjs --update || failures=$((failures + 1))

judge_baseline \
  .interface-baseline.json \
  interface-baseline-update \
  go run ./scripts/contracts/layering --update || failures=$((failures + 1))

# The declared MCP response contract. Regeneration derives every shape by
# invoking the shipped handlers in-process, so a hand-edited field list, a
# hand-edited undeclared_baseline, or a response change nobody re-froze all
# show up here as a byte difference.
judge_baseline \
  .mcp-response-contract.json \
  response-contract-update \
  env UPDATE_GOLDEN=1 go test ./cmd/browser-agent/internal/responsegate \
  -run TestDeclaredResponseShapesStillShip -count=1 || failures=$((failures + 1))

if [[ "$failures" -ne 0 ]]; then
  echo "FAIL: $failures ratchet baseline(s) do not match the tree." >&2
  exit 1
fi
echo "OK: all ratchet baselines are current."
